/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



public class home extends javax.swing.JFrame {

    /**             
     * Creates new form home
     */
    public home() {
        initComponents();
       
   
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(4, 16, 34));
        jButton1.setForeground(new java.awt.Color(78, 161, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/add-user.png"))); // NOI18N
        jButton1.setText("New Student");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 78, 168)));
        jButton1.setPreferredSize(new java.awt.Dimension(159, 57));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 160, 80));

        jButton2.setBackground(new java.awt.Color(4, 16, 34));
        jButton2.setForeground(new java.awt.Color(78, 161, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/book.png"))); // NOI18N
        jButton2.setText("New Book");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 78, 168)));
        jButton2.setPreferredSize(new java.awt.Dimension(159, 57));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 160, 80));

        jButton3.setBackground(new java.awt.Color(4, 16, 34));
        jButton3.setForeground(new java.awt.Color(78, 161, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/bar-chart.png"))); // NOI18N
        jButton3.setText("Statistics");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 78, 168)));
        jButton3.setPreferredSize(new java.awt.Dimension(159, 57));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 160, 80));

        jButton4.setBackground(new java.awt.Color(4, 16, 34));
        jButton4.setForeground(new java.awt.Color(78, 161, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/issue.png"))); // NOI18N
        jButton4.setText("Issue book");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 78, 168)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 160, 80));

        jButton5.setBackground(new java.awt.Color(4, 16, 34));
        jButton5.setForeground(new java.awt.Color(78, 161, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/return book.png"))); // NOI18N
        jButton5.setText("Return Book");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 78, 168)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 160, 80));

        jButton6.setBackground(new java.awt.Color(4, 16, 34));
        jButton6.setForeground(new java.awt.Color(78, 161, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/information.png"))); // NOI18N
        jButton6.setText("Display Info");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 78, 168)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 160, 80));

        jButton7.setBackground(new java.awt.Color(4, 16, 34));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(78, 161, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/logout.png"))); // NOI18N
        jButton7.setText("Logout");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 78, 168)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2/homepage2Back.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        setSize(new java.awt.Dimension(714, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setVisible(false);
        new DisplayStudentAndBooks().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       setVisible(false);
        new newStudent().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new newBook().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new IssueBook1().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new returnBook().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new statistics().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
